export { getUpcomingMovies } from './getUpcomingMovies';
export { getTrendingMovies } from './getTrendingMovies';
export { getPopularSeries } from './getPopularSeries';
export { getOneMovieGenres } from './getOneMovieGenre';
export { getOneMovieTrailer } from './getMovieTrailer';
export { getMoviesGenres, getSeriesGenres } from './getMovieGenres';
export { getAiringTodaySeries } from './getAiringTodaySeries';
export { getTopRatedSeries } from './getTopRatedSeries';
export { getTodaysTrendingMovies } from './getTodaysTrendingMovies';
export { getOnTheAirSeries } from './getOnTheAirSeries';
export { getMovieInfoById } from './getMovieInfoById';
export { getMovieActorsById } from './getMovieActorsById';
export { getSeriesInfoById } from './getSeriesInfoById';
export { getSeriesActorsById } from './getSeriesActorsById';
export { getMoviesByGenreId } from './getMoviesByGenreId';
export { getSeriesByGenreId } from './getSeriesByGenreId';
export { getMovies } from './getMovies';
