export { Header } from './Header';
export { Footer } from './Footer';
export { Menu } from './Menu';
export { Button } from './Button';
export { SearchBox } from './SearchBox';
export { Logo } from './Logo';
export { MovieInfo } from './MovieInfo';
export { Trailer } from './MovieTrailer';
export { Modal } from './Modal';
